import fs from 'node:fs';
const required=['index.html','vercel.json','package.json','.github/workflows/daily-reels.yml','.github/workflows/24x7-watchdog.yml','api/run-reels.js','api/status.js','api/batch.js','api/approval.js','api/scout.js','scripts/daily_reels.py','scripts/production_hotfix.py','src/App.tsx','src/lib/production-service.ts','src/lib/media-renderer.ts'];
for(const file of required)if(!fs.existsSync(file))throw new Error('Missing required file: '+file);
const py=fs.readFileSync('scripts/daily_reels.py','utf8');
for(const marker of ['def render_reel','def commons_search','def download_assets','def trends'] )if(!py.includes(marker))throw new Error('Production marker missing: '+marker);
const service=fs.readFileSync('src/lib/production-service.ts','utf8');
for(const marker of ['findAndDownloadWikimedia','renderVerticalReel','runQualityChecks'])if(!service.includes(marker))throw new Error('Browser production marker missing: '+marker);
const app=fs.readFileSync('src/App.tsx','utf8');
for(const marker of ['ProductionDashboard','ProductionPipeline','ApprovalScreen','productionService'])if(!app.includes(marker))throw new Error('Frontend marker missing: '+marker);
console.log('FESTIVAL OF BHARAT V3 BUILD CHECK PASSED');